### PR TITLE
Update some dependencies and build on GitHub

### PR DESCRIPTION
**Pull request by garydgregory**
- Jetty 9 to 10
- Hibernate 5.6.12.Final to 5.6.14.Final
- Spring Boot 2.7.4 to 2.7.5
- Add a default Maven goal
- Use GitHub Dependabot once a week
- Use GitHub Actions

### CODE REVIEW

**Comment by garydgregory** [comment]
For me, the build passes locally on Windows, these are odd permission failures.

**Comment by jamesbognar** [comment]
That should be writing to the working directory (./jetty-thread-dump-0.log), not the root directory.  Not sure why it's ending up in root.

**Comment by garydgregory** [comment]
> That should be writing to the working directory (./jetty-thread-dump-0.log), not the root directory. Not sure why it's ending up in root.

I fixed that in this branch.

**Comment by garydgregory** [comment]
Hi @jamesbognar,

Any thoughts on the broken pipe failures? Do you see this failure in a local build of this branch?

**Comment by jamesbognar** [comment]
@garydgregory - I'll have to check out your branch and try it myself.  I won't be able to get to it today though.

**Comment by garydgregory** [comment]
Hi @jamesbognar Would you be able to check this branch soon?

**Comment by jamesbognar** [comment]
I don't know why the maven build fails in GitHub.  I tested it locally and these changes were fine.  I merged your changes and the Jenkins build results were fine indicating that there isn't a regression: 
https://ci-builds.apache.org/blue/organizations/jenkins/Juneau%2FJuneau-Java-11/detail/Juneau-Java-11/755/pipeline

**Comment by garydgregory** [comment]
@jamesbognar 
I've seen broken pipe errors in a completely different context in the past: Between a JDBC driver and a database when after a long period of inactivity, the database side closes the connection, and when the client tries to use the connection, it fails with a broken pipe error message. 
Could something similar be happening here? A server closes a socket when the client does not expect it? It seems unlikely but there is something about this environment that is working for the build :-(

**Comment by jamesbognar** [comment]
In this case the broken pipe is in the HTTP layer.  These tests should be running at most around 10 seconds.  It's really just HttpClient encountering a broken pipe trying to read from the servlet.  Something wonky is going on with the network layer in the build environment.  I'm curious to know if it's repeatable.  Only 22 of the 1000 tests actually failed.

**Comment by garydgregory** [comment]
Green build!

**Pull request merged**
