### PR TITLE
adding missing config command in spring boot example

### PR DESCRIPTION
**Pull request by Akayeshmantha**

### CODE REVIEW

**Comment by jamesbognar** [comment]
@Akayeshmantha - Can you add this command to the other configs as well?

juneau-examples-rest-jetty/examples.cfg
juneau-microservice-jetty-template/my-microservice.cfg
juneau-microservice-springboot-template/src/main/resources/juneau.cfg

**Comment by Akayeshmantha** [comment]
Sure @jamesbognar  gimme a minute

**Comment by Akayeshmantha** [comment]
@jamesbognar  added.

And I noticed on juneau-microservice-springboot-template/src/main/resources/juneau.cfg the logger settings are also not there shall I add them also James

**Comment by jamesbognar** [comment]
Oh wait....console commands don't apply to Spring Boot because it's not using the Microservice API.   The same applies for the logging settings.  So only add this command to the jetty template and examples.

**Comment by Akayeshmantha** [comment]
got it @jamesbognar  James did that

**Comment by Akayeshmantha** [comment]
Thanks @jamesbognar  James

**Pull request merged**
