### PR TITLE
adding oapi samples

### PR DESCRIPTION
**Pull request by Akayeshmantha**

### CODE REVIEW

**Comment by jamesbognar** [comment]
Awesome!  The OpenAPI support is very new.  Let me know if you have any implementation suggestions.

**Comment by Akayeshmantha** [comment]
@jamesbognar  yes James looking at the current spec to get more idea on openApi spec at https://github.com/OAI/OpenAPI-Specification

**Comment by jamesbognar** [comment]
@Akayeshmantha - FYI...the current OpenAPI support is based on Swagger 2.0 not OpenAPI 3.0.  Due to lack of time, I decided to stick with Swagger 2.0 and leave OpenAPI 3.0 support for future work.  I'd be happy if you wanted to do some work bringing it up to the latest spec!  I don't know how difficult that will be though.

**Comment by Akayeshmantha** [comment]
@jamesbognar  that's a great news James will start working on it thanks alot

**Pull request merged**
