### PR TITLE
Added config command for microservice CLI

### PR DESCRIPTION
**Pull request by shalithasuranga**
config [get|set]

config get <key> 
This will output value for given section/key or key

config set <key> <value>
This will change current configuration

### CODE REVIEW

**Comment by jamesbognar** [comment]
Thanks!

**Comment by jamesbognar** [comment]
I noticed one issue.  You should call commit() on the Config object to make sure your change gets persisted.  It's similar to a database transaction.  Once you call commit, it triggers registered listeners.

**Comment by shalithasuranga** [comment]
Yeah it is good to persist the configuration to original config file. I will update via a PR 
Thanks

**Comment by CraigLRussell** [comment]
I'm not completely clear on our coding/testing standards, so take these as you will.

The config command doesn't check for too many arguments but just ignores them. 

There are no test cases. Do we usually expect test cases (at least unit tests) for new features?

**Comment by shalithasuranga** [comment]
Hi.. Craig

Thanks for the feedback. Yes additional arguments are ignored. I will update by adding
 "Too many arguments" output as well

I checked about console command unit tests. But it seems there are no tests for existing console commands. So that's why I didn't add tests just for new `ConfigCommand`

Please advice how this can be improve further

**Comment by shalithasuranga** [comment]
too many arguments check added [here](https://github.com/apache/juneau/pull/20)

**Comment by jamesbognar** [comment]
The command API is currently in its infancy.  I don't see a good way to test them yet.  

I should figure out a way of invoking them programmatically for testing purposes.  Something simple on the Microservice class like:
`public String invokeCommand(String name, Object...args) throws Exception`

Then this can be used from a RestTestcase which automatically takes care of initializing a microservice.  I can add a method to this class for retrieving the microservice:

`public static RestMicroservice getMicroservice();`

**Pull request merged**
