### PR TITLE
adding sample description for core examples in overview.html

### PR DESCRIPTION
**Pull request by Akayeshmantha**
@jamesbognar added a simple description on core samples James.

### CODE REVIEW

**Comment by jamesbognar** [comment]
Thanks!  This will be live when I regenerate the javadocs later today.

**Comment by Akayeshmantha** [comment]
Sure @jamesbognar.So would like to contribute on Spring boot examples.Any one started working on it?

**Comment by jamesbognar** [comment]
Sure!  But FYI...the Spring Boot integration API might still be in flux.  I just did some significant refactoring in the past two days.  Here's the updated documentation (still working on it):
http://juneau.apache.org/site/apidocs-8.0.0/overview-summary.html#juneau-rest-server-springboot

The documentation (which I'm working on today) will describe how to deploy the REST examples as a Spring Boot application on the Heroku cloud platform.  
https://juneau-example.herokuapp.com/

Also, I'm relatively new to Spring and Spring Boot, so design/implementation suggestions are welcome.

**Comment by Akayeshmantha** [comment]
Got it James

**Comment by Akayeshmantha** [comment]
@jamesbognar I saw Packaging as WAR files in juneau-examples-rest todo file is this something pending

**Pull request merged**
