### PR TITLE
Migration to openapi spe 3.0

### PR DESCRIPTION
**Pull request by Akayeshmantha**
@jamesbognar James started working on openapi spec 3.Want to make sure that I am on the right path since am a newbie.Will be pushing all changes to this pull request hope we can keep the pull request open till we push all the changes.

### CODE REVIEW

**Comment by jamesbognar** [comment]
You're working fast!

This looks good so far.  It looks like you're using the Swagger DTO as a guide which is good since it's likely a subset of OpenAPI.  

I'd like to get 8.0.0 out the door before we pull in these changes, so we have time to develop this.

**Comment by Akayeshmantha** [comment]
Thank you James.Yes am referring Swagger DTO as the guide.Will work soon on this.

**Comment by Akayeshmantha** [comment]
@jamesbognar James any reason to drop Path Item Object,Path object from dto-swagger.

**Comment by jamesbognar** [comment]
I didn't implement a Paths object because it could be represented as a Map<String,OperationMap>.  I see no reason why we shouldn't add it though.

**Comment by Akayeshmantha** [comment]
Yes true that @jamesbognar.It can be represented with OperationMap.Thank you for the clarification.

**Comment by jamesbognar** [comment]
@Akayeshmantha - Now that 8.0.0 has been released, we can merge this pull request whenever you think you're ready.

**Comment by Akayeshmantha** [comment]
Hi @jamesbognar am working on this soon.Btw any idea to participate in gsoc 19 ?

**Comment by jamesbognar** [comment]
Unlikely.  Although it would be cool to do so, I'm pretty busy as-is.

**Comment by Akayeshmantha** [comment]
To be honest @jamesbognar James me and Shalitha thought to work on gsoc internships.So since we have context on juneau we thought it would be good to do it for juneau.If you can let us know two compnents that we can work on.We can do a background research and work on the time taking stuffs like application filling and all 🙂

**Comment by jamesbognar** [comment]
@Akayeshmantha , @shalithasuranga - 

You might want to take a look at what Marcelo is working on.  It looks interesting and he's looking for help.
https://github.com/marcelosv/juneau/issues/1

**Pull request merged**
